### ISSUE TITLE
Promises change

### ISSUE THREAD

**Issue by jrgleason** [anthonybennett/anthonybennett.github.io#2]
I would probably use the normal Q promises instead of done https://github.com/kriskowal/q. This would be .then instead of .done. This is more generic and explains non-ajax ways of doing stuff.

Like this...

Q.fcall(promisedStep1)
.then(promisedStep2)
.then(promisedStep3)
.then(promisedStep4)
.then(function (value4) {
    // Do something with value4
})
.catch(function (error) {
    // Handle any error from all above steps
})
.done();

Just a thought.

**Comment by anthonybennett** [comment]
I was trying to stick to things folks are familiar with (i.e. jQuery), but there are definitely better solutions out there. :)

**Comment by jrgleason** [comment]
Cool yeah promises are a presentation in themselves but showing chaining might hhelpwith the why question
