### ISSUE TITLE
More complicated this example

### ISSUE THREAD

**Issue by jrgleason** [anthonybennett/anthonybennett.github.io#3]
I think you just skimmed the surface and there maybe more to what you said. For example this Angular code (http://plnkr.co/edit/cfqygl1P13MsWz3Bgc0X)...

```
var app = angular.module('plunker', []);
app.controller('MainCtrl', function($scope, $interval) {
   $scope.name = 'World';
   this.value = "Start";
   this.test = function(){
     console.log(this.value);
   }
   $interval(function(){
      this.test(); // Undefined
    }, 1000)
 });
```

Covering this type of thing might help as well.

**Comment by anthonybennett** [comment]
I could definitely have gone into way more detail, but due to the time constraints, I had to trim back. Maybe if I give a 2-hour version of this talk someday, I'll have a chance to dive in deeper. Thanks for the sample code!

**Comment by jrgleason** [comment]
The sample from the Netflix talk was better and used straight Array.forEach instead
